name: Periodic Deployment

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

  deploy:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitHub
        run: |
          git config --global user.email ""
          git config --global user.name "Monu"
          git add .
          git commit -m "Automated commit every 5 minutes" 
          git push
