name: Auto Push to Git every 2 minutes

on:
  schedule:
    - cron: '*/2 * * * *' # Runs every 2 minutes

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      
      - name: Commit and push changes
        run: |
          git commit -am "Auto-commit $(date +%s)"
          git push
